### ISSUE TITLE
What's the difference between Precog and PrecogOnline?

### ISSUE THREAD

**Issue by psy-mas** [ansjin/memory_leak_detection#1]
Hi, thank you for contributing such an awesome work.
I encountered some problems while reading the paper and the code. Would you please explain **what's the differen between Precog and PrecogOnline**?
Appreciate it very much!

**Comment by ansjin** [comment]
PrecogOnline works in an online fashion, where it takes point by point and do the prediction. The main change between the two is how linear regression is done (```do_linear_regression´´´ function). PrecogOnline performs the linear regression in an online fashion, therefore it does not require the previous points instead the current point and calculates the fitness of the current point to the previous trend line. Also, one does not require extra training in this algorithm, it keeps updating the training trends. 


On the other hand, in Precog for evaluation a window of points is required where the linear regression is calculated. In this, for updating the training trends, one has to perform the training on all the data. 

Additionally, it also keeps updating the average values of the points used within the linear regression

**Comment by psy-mas** [comment]
Thanks for the answer, I got it now.
Would the PrecogOnline perform better in time consumption and F1？ It seems the PrecogOnline is less complex and more suitable for online deployment.

**Comment by psy-mas** [comment]
Thanks for the detailed explanation. No more questions by now, I am closing this issue.
